# Generated by Django 5.2.13 on 2026-04-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_content_en_news_content_ru_news_content_uz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
