# Generated by Django 5.2.13 on 2026-04-27 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('score', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Service types',
                'db_table': 'service_type',
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('APPROVED', 'Approved'), ('CANCELED', 'Canceled')], default='IN_PROGRESS', max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(related_name='services', to='shared.media')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_services', to='services.servicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_services',
            },
        ),
        migrations.CreateModel(
            name='UserServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, choices=[('IN_PROGRESS', 'In progress'), ('APPROVED', 'Approved'), ('CANCELED', 'Canceled')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('APPROVED', 'Approved'), ('CANCELED', 'Canceled')], max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.userservice')),
            ],
            options={
                'db_table': 'user_service_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userservice',
            index=models.Index(fields=['user', 'status'], name='user_servic_user_id_c12c10_idx'),
        ),
        migrations.AddIndex(
            model_name='userservice',
            index=models.Index(fields=['service_type', 'status'], name='user_servic_service_60fc49_idx'),
        ),
        migrations.AddIndex(
            model_name='userservicestatushistory',
            index=models.Index(fields=['user_service', '-created_at'], name='user_servic_user_se_c3bf13_idx'),
        ),
    ]
