# Generated by Django 5.2.13 on 2026-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appversion_device_permission_endpoint_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, default=9876545678, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
