# Generated by Django 5.2.13 on 2026-04-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('RU', 'Russian'), ('EN', 'English'), ('CRL', 'Cyrillic'), ('UZ', 'Uzbek')], max_length=5, null=True),
        ),
    ]
