# Generated by Django 5.2.13 on 2026-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appversion',
            name='is_force',
            field=models.BooleanField(default=False),
        ),
    ]
